### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/spectrum#1]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by Kunal1198** [comment]
Hi @t0xic0der , can I work on this.

**Comment by gridhead** [comment]
Sure. I am assigning this issue to you.

Feel free to leave a star at the repository if you find it useful.

**Comment by Kunal1198** [comment]
Please review my PR #7 @t0xic0der
