### ISSUE TITLE
Facilitate Go module support

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/spectrum#14]
@pedroandrade, you did it for t0xic0der/prudence. Would you want to pick it for this one?

**Comment by pedroandrade** [comment]
for sure :D, I'll pick this one

**Comment by gridhead** [comment]
Cool. I have assigned you the issue.

**Comment by gridhead** [comment]
Any updates, @pedroandrade? :sweat_smile:

**Comment by pedroandrade** [comment]
@t0xic0der done :D sorry about time, I've had a very busy week

**Comment by gridhead** [comment]
Not a problem. :smile:
