### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/spectrum#2]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by yash2189** [comment]
Hi can I work on this?

**Comment by gridhead** [comment]
Sure. I am assigning this issue to you.

Feel free to leave a star at the repository if you find it useful.

**Comment by yash2189** [comment]
@t0xic0der Please review my PR #8
