### ISSUE TITLE
Add customizable WARNING text line for CLI

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/spectrum#3]
Note the following points.
- The base color for denoting texts is suggested to be `YELLOW`.
- Use the exclamatory sign `[ ! ]` or `[WARNING]` text to be the symbol.
- Make sure the typeface on the CLI is in `BOLD` style.

**Comment by 0vj** [comment]
Hi. I love work on this. may i work on this ?

**Comment by gridhead** [comment]
Sure. I will assign this issue to you.

**Comment by gridhead** [comment]
@mr-tafreshi Feel free to leave a star at the repository if you find it helpful.

**Comment by 0vj** [comment]
Bold and capital ? or only bold ?

**Comment by gridhead** [comment]
Check https://github.com/t0xic0der/spectrum/issues/4#issuecomment-710134563. Also, I am currently unassigning you from this issue as #4 has already been assigned to you. Please complete that and then this would be assigned to you.

**Comment by moogacs** [comment]
@t0xic0der  I will pick that one

**Comment by gridhead** [comment]
@moogacs,

**Asking politely for an assignment would be appreciated.**

The maintainers of this repository spend countless hours into QAing the project and checking the kinds of stuff which can be added so the least, the contributors can do is to ask for issue assignment politely and not state that you are taking it right away.

For your reference @VaibhavSaini19 @shivangswain @s-katte @tripathyprateek

**Comment by moogacs** [comment]
@t0xic0der  

I have deleted & closed the pull request, the issue wasn't assigned I don't think it's a big problem to start work on it, countless hours into QA-ing the project !, anyway have fun with your project

**Comment by VaibhavSaini19** [comment]
@moogacs Thank you for taking the time to close that PR yourself. Saved the maintainer's work to deal with unnecessary things. Of course, it is not a big deal to start working on something you wish to collaborate on, but unlike you (who doesn't even have the time to read the [Contributing Guidelines](https://github.com/t0xic0der/spectrum/blob/main/CONTRIBUTING.md) of the project), the repo owners actually put efforts in maintaining the project and expect the same in return from the community. If you can't even do that, it is better you find something else to spend your time on.

**Comment by 0vj** [comment]
Hi,can you reassign it to me ?

**Comment by gridhead** [comment]
Sure @mr-tafreshi. I am assigning this to you.

**Comment by 0vj** [comment]
Done. #16

**Comment by gridhead** [comment]
Great work done. @mr-tafreshi 

Closing #3 via #16.
