### ISSUE TITLE
Add customizable SUCCESS text line for CLI

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/spectrum#4]
Note the following points.
- The base color for denoting texts is suggested to be `GREEN`.
- Use the ASCII stroke tick sign or `[SUCCESS]` text to be the symbol.
- Make sure the typeface on the CLI is in `BOLD` style.

**Comment by 0vj** [comment]
wow. may i work on this ? im noob in golang :))))

**Comment by gridhead** [comment]
This issue does not need much expertise anyway. :+1: 

I am assigning this to you. Feel free to leave a star at this repository if you find it helpful.

**Comment by 0vj** [comment]
Bold and capital ? or only bold ?

**Comment by gridhead** [comment]
Bold and capital. The same has been mentioned clearly in the issue description too. :smile:

**Comment by 0vj** [comment]
background green or font color green ?

**Comment by 0vj** [comment]
And what should I choose the name of the function?

**Comment by gridhead** [comment]
Try `HD_SUCCESS` maybe. :wink:

**Comment by gridhead** [comment]
> background green or font color green ?

Only the font color should be green.

**Comment by 0vj** [comment]
pr #10

**Comment by gridhead** [comment]
Resolved #4 via #10.
