### ISSUE TITLE
Add customizable FAILURE text line for CLI

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/spectrum#5]
Note the following points.
- The base color for denoting texts is suggested to be `RED`.
- Use the ASCII stroke cross sign or `[FAILURE]` text to be the symbol.
- Make sure the typeface on the CLI is in `BOLD` style.

**Comment by guigui64** [comment]
Hi @t0xic0der can you assign this issue to me ?

**Comment by gridhead** [comment]
Sure @guigui64. I am assigning this issue to you. 

Feel free to leave a star at this repository if you find it helpful.
