### ISSUE TITLE
Add customizable DETAILS text line for CLI

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/spectrum#6]
Note the following points.
- The base color for denoting texts is suggested to be `BLUE`.
- Use the ASCII letter `[ i ]` or `[DETAILS]` text to be the symbol.
- Make sure the typeface on the CLI is in `BOLD` style.

**Comment by guigui64** [comment]
Hi @t0xic0der can you assign this issue to me ?

**Comment by gridhead** [comment]
I have assigned https://github.com/t0xic0der/spectrum/issues/5 to you. Please complete that first.

**Comment by VictorAssunc** [comment]
I would like to deal with this. If you're really going to wait for him to finish, I can get this one.

**Comment by gridhead** [comment]
Cool. I am assigning this to you. @VictorAssunc.

Leave a star at this repository, should you find it useful.
